### ISSUE TITLE
apoc-common 2025.06.0 unusable due to broken dependencies

### ISSUE THREAD

**Issue by jonibonicodi** [neo4j/apoc#799]
I discovered, that from version **2025.06.0** the library **apoc-common** contains a wrong dependency to **netty-bom** as jar, which causes builds including this library to fail. 
 
- Neo4j version: 2025.06.0
- Library "org.neo4j.procedure.apoc-common" in version "2025.06.0" has a dependency to "io.netty:netty-bom:jar:4.2.1.Final (compile)"
- Installation method: maven

### Steps to reproduce
- add depdency to your maven build:
`     <dependency>`
`        <groupId>org.neo4j.procedure</groupId>`
`        <artifactId>apoc-common</artifactId>`
`        <version>2025.06.0</version>`
`    </dependency>`

### Expected behavior
 It's possible to compile
### Actual behavior
Impossible to compile, because the dependency "io.netty:netty-bom" is not a "jar" library, but just a bom.

### maven build log

[ERROR] Failed to execute goal on project 'project-name': Could not resolve dependencies for project 'project-name/version'
[ERROR] dependency: io.netty:netty-bom:jar:4.2.1.Final (compile)
[ERROR] 	Could not find artifact io.netty:netty-bom:jar:4.2.1.Final in 'repo'

**Comment by hvub** [comment]
Looks the same as: https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/4449

**Comment by hvub** [comment]
Trying to understand you setup: What are you building with maven? Your own procedure project? Do you also have neo4j as a dependency?

**Comment by jonibonicodi** [comment]
Yes, exactly. 

`    <properties>`
`        <java.version>21</java.version>`
`        <maven.compiler.source>${java.version}</maven.compiler.source>`
`        <maven.compiler.target>${java.version}</maven.compiler.target>`
`        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`
`        <jacoco-plugin.version>0.8.13</jacoco-plugin.version>`
`        <neo4j.version>2025.06.0</neo4j.version>`
`    </properties>`
`       <dependency>`
`            <groupId>org.neo4j</groupId>`
`            <artifactId>neo4j</artifactId>`
`            <version>${neo4j.version}</version>`
`        </dependency>`
`        <dependency>`
`            <groupId>org.neo4j.procedure</groupId>v
`            <artifactId>apoc-common</artifactId>`
`            <version>${neo4j.version}</version>`
`        </dependency>`
`        <dependency>`
`            <groupId>org.neo4j.test</groupId>`
`            <artifactId>neo4j-harness</artifactId>`
`            <version>${neo4j.version}</version>`
`            <scope>test</scope>`
`        </dependency>`

**Comment by gem-neo4j** [comment]
We made the netty bump on our end, so I this should be resolved.

**Comment by jonibonicodi** [comment]
It's not resolved. The issue remains the same up to the 2025.09.0 version. 
Upgrading netty version doesn't resolve this. 
The problem is the "type" of the dependency. 
As I described above, netty-bom is of type "pom" and not of type "jar". 
Without manual exclusions, apoc-common library is currently unusable for several months now.

**Comment by loveleif** [comment]
You're correct @jonibonicodi, and I apologize for the confusion and delay. Fix is [here](https://github.com/neo4j/apoc/pull/853) (hopefully).
